#!/usr/bin/env node

/* eslint-disable */
var program = require('commander')

program
  .version('0.1.0')
  .command('component [name]', 'create react component')
  .command('redux [name]', 'create redux module')
  .parse(process.argv);
